### ISSUE TITLE
include INSTALL instructions

### ISSUE THREAD

**Issue by arthurlutz** [fictive-kin/webshell#15]
It would be nice to have install instructions somewhere in the package.

**Comment by scoates** [comment]
agreed, we need to document this; it's now in NPM, though:

npm install webshell

(leaving open to add to README)

**Comment by funkatron** [comment]
I believe that this has been updated appropriately by cb38ad89551a734b8d42eeb360df2146131dd2ed  and 527bccb44071007c4872b076bf01928385fb4682
